# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - giuseppeCoccia
  - julianmack
  - SamG97
  - samgd

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# A list of keywords that skip the process to auto-add reviewers if pull
# requests include them:
skipKeywords:
   - "not ready"
