gitlab-runner:
  # The GitLab Server URL (with protocol) that want to register the runner
  # against.
  #
  # https://docs.gitlab.com/runner/commands/README.html#gitlab-runner-register
  gitlabUrl: https://gitlab.com/

  # The registration token for adding new Runners to the GitLab server. This
  # must be retrieved from your GitLab instance.
  runnerRegistrationToken: "TODO_CHANGE"

  rbac:
    create: true

  # Configuration for the Pods that the runner launches for each new job.
  runners:
    # Run all containers with the privileged flag enabled
    # This will allow the docker:stable-dind image to run if you need to run
    # Docker commands. Please read the docs before turning this on:
    #   https://docs.gitlab.com/runner/executors/kubernetes.html#using-docker-dind
    privileged: true

    # Namespace to run Kubernetes jobs in (defaults to 'default')
    namespace: gitlab-ci

    # Build container specific configuration.
    #
    # Ideally need nodeSelector/tolerations/GPU limits, not available yet:
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/3959
    builds:
      cpuLimit: 3000m
      memoryLimit: 10Gi
      cpuRequests: 3000m
      memoryRequest: 10Gi

    env:
      # hotfix for https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
      DOCKER_TLS_CERTDIR: ""
